### ISSUE TITLE
Notation error in convolutions first and missing link for module 5

### ISSUE THREAD

**Issue by Benjamin-Loison** [dataflowr/website#21]
1. It seems that [the line 117 in modules/extras/Convolutions_first.md](https://github.com/dataflowr/website/blob/66ef0c2ba122fd59f305302126ef1cd11d92cafc/modules/extras/Convolutions_first.md?plain=1#L117) (better viewable here: https://dataflowr.github.io/website/modules/extras/Convolutions_first/)

Should be:
`y_j = \sum_\ell (C_\ba)_{j\ell}x_\ell = \sum_\ell a_{j-\ell}x_\ell,`
and not:
`y_j = \sum_\ell (C_\ba)_{j\ell}x_\ell = \sum_\ell a_{\ell-j}x_\ell,`

2. It seems that the notebook link to https://github.com/dataflowr/notebooks/blob/master/Module5/Stacking_layers_MLP_CIFAR10.ipynb is missing on https://dataflowr.github.io/website/modules/5-stacking-layers/

**Comment by mlelarge** [comment]
Corrected. Thank you very much!
https://github.com/dataflowr/website/commit/1c977a8c58b3e985dc12f0567877e1fd0a521c18
